run:
  go: "1.21"
  timeout: 5m

linters:
  enable:
    - bodyclose
    - errname
    - gocritic
    - goimports
    - misspell
    - prealloc

linters-settings:
  goimports:
    local-prefixes: github.com/alijayanet/gembok-backend
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
  exclude-rules:
    - path: _test\.go
      linters:
        - gocritic
