// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	entities "github.com/alijayanet/gembok-backend/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// CronScheduleRepository is an autogenerated mock type for the CronScheduleRepository type
type CronScheduleRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: schedule
func (_m *CronScheduleRepository) Create(schedule *entities.CronSchedule) error {
	ret := _m.Called(schedule)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.CronSchedule) error); ok {
		r0 = rf(schedule)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *CronScheduleRepository) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindActive provides a mock function with no fields
func (_m *CronScheduleRepository) FindActive() ([]*entities.CronSchedule, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindActive")
	}

	var r0 []*entities.CronSchedule
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*entities.CronSchedule, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*entities.CronSchedule); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.CronSchedule)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: id
func (_m *CronScheduleRepository) FindByID(id uint) (*entities.CronSchedule, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entities.CronSchedule
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*entities.CronSchedule, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *entities.CronSchedule); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.CronSchedule)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByTaskType provides a mock function with given fields: taskType
func (_m *CronScheduleRepository) FindByTaskType(taskType string) (*entities.CronSchedule, error) {
	ret := _m.Called(taskType)

	if len(ret) == 0 {
		panic("no return value specified for FindByTaskType")
	}

	var r0 *entities.CronSchedule
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entities.CronSchedule, error)); ok {
		return rf(taskType)
	}
	if rf, ok := ret.Get(0).(func(string) *entities.CronSchedule); ok {
		r0 = rf(taskType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.CronSchedule)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(taskType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: schedule
func (_m *CronScheduleRepository) Update(schedule *entities.CronSchedule) error {
	ret := _m.Called(schedule)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.CronSchedule) error); ok {
		r0 = rf(schedule)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCronScheduleRepository creates a new instance of CronScheduleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCronScheduleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CronScheduleRepository {
	mock := &CronScheduleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
