// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	entities "github.com/alijayanet/gembok-backend/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// InvoiceRepository is an autogenerated mock type for the InvoiceRepository type
type InvoiceRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: invoice
func (_m *InvoiceRepository) Create(invoice *entities.Invoice) error {
	ret := _m.Called(invoice)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.Invoice) error); ok {
		r0 = rf(invoice)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *InvoiceRepository) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: page, perPage
func (_m *InvoiceRepository) FindAll(page int, perPage int) ([]*entities.Invoice, int64, error) {
	ret := _m.Called(page, perPage)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*entities.Invoice
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int) ([]*entities.Invoice, int64, error)); ok {
		return rf(page, perPage)
	}
	if rf, ok := ret.Get(0).(func(int, int) []*entities.Invoice); ok {
		r0 = rf(page, perPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Invoice)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) int64); ok {
		r1 = rf(page, perPage)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(int, int) error); ok {
		r2 = rf(page, perPage)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByCustomerID provides a mock function with given fields: customerID, page, perPage
func (_m *InvoiceRepository) FindByCustomerID(customerID uint, page int, perPage int) ([]*entities.Invoice, int64, error) {
	ret := _m.Called(customerID, page, perPage)

	if len(ret) == 0 {
		panic("no return value specified for FindByCustomerID")
	}

	var r0 []*entities.Invoice
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(uint, int, int) ([]*entities.Invoice, int64, error)); ok {
		return rf(customerID, page, perPage)
	}
	if rf, ok := ret.Get(0).(func(uint, int, int) []*entities.Invoice); ok {
		r0 = rf(customerID, page, perPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Invoice)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, int, int) int64); ok {
		r1 = rf(customerID, page, perPage)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(uint, int, int) error); ok {
		r2 = rf(customerID, page, perPage)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByID provides a mock function with given fields: id
func (_m *InvoiceRepository) FindByID(id uint) (*entities.Invoice, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entities.Invoice
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*entities.Invoice, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *entities.Invoice); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Invoice)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByNumber provides a mock function with given fields: number
func (_m *InvoiceRepository) FindByNumber(number string) (*entities.Invoice, error) {
	ret := _m.Called(number)

	if len(ret) == 0 {
		panic("no return value specified for FindByNumber")
	}

	var r0 *entities.Invoice
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entities.Invoice, error)); ok {
		return rf(number)
	}
	if rf, ok := ret.Get(0).(func(string) *entities.Invoice); ok {
		r0 = rf(number)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Invoice)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(number)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByStatus provides a mock function with given fields: status, page, perPage
func (_m *InvoiceRepository) FindByStatus(status string, page int, perPage int) ([]*entities.Invoice, int64, error) {
	ret := _m.Called(status, page, perPage)

	if len(ret) == 0 {
		panic("no return value specified for FindByStatus")
	}

	var r0 []*entities.Invoice
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(string, int, int) ([]*entities.Invoice, int64, error)); ok {
		return rf(status, page, perPage)
	}
	if rf, ok := ret.Get(0).(func(string, int, int) []*entities.Invoice); ok {
		r0 = rf(status, page, perPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Invoice)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int, int) int64); ok {
		r1 = rf(status, page, perPage)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(string, int, int) error); ok {
		r2 = rf(status, page, perPage)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindLastInvoiceNumber provides a mock function with no fields
func (_m *InvoiceRepository) FindLastInvoiceNumber() (*entities.Invoice, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindLastInvoiceNumber")
	}

	var r0 *entities.Invoice
	var r1 error
	if rf, ok := ret.Get(0).(func() (*entities.Invoice, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *entities.Invoice); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Invoice)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: invoice
func (_m *InvoiceRepository) Update(invoice *entities.Invoice) error {
	ret := _m.Called(invoice)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.Invoice) error); ok {
		r0 = rf(invoice)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewInvoiceRepository creates a new instance of InvoiceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInvoiceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *InvoiceRepository {
	mock := &InvoiceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
