// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	entities "github.com/alijayanet/gembok-backend/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// ONULocationRepository is an autogenerated mock type for the ONULocationRepository type
type ONULocationRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: location
func (_m *ONULocationRepository) Create(location *entities.ONULocation) error {
	ret := _m.Called(location)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.ONULocation) error); ok {
		r0 = rf(location)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *ONULocationRepository) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: page, perPage
func (_m *ONULocationRepository) FindAll(page int, perPage int) ([]*entities.ONULocation, int64, error) {
	ret := _m.Called(page, perPage)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*entities.ONULocation
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int) ([]*entities.ONULocation, int64, error)); ok {
		return rf(page, perPage)
	}
	if rf, ok := ret.Get(0).(func(int, int) []*entities.ONULocation); ok {
		r0 = rf(page, perPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.ONULocation)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) int64); ok {
		r1 = rf(page, perPage)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(int, int) error); ok {
		r2 = rf(page, perPage)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByCustomerID provides a mock function with given fields: customerID
func (_m *ONULocationRepository) FindByCustomerID(customerID uint) (*entities.ONULocation, error) {
	ret := _m.Called(customerID)

	if len(ret) == 0 {
		panic("no return value specified for FindByCustomerID")
	}

	var r0 *entities.ONULocation
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*entities.ONULocation, error)); ok {
		return rf(customerID)
	}
	if rf, ok := ret.Get(0).(func(uint) *entities.ONULocation); ok {
		r0 = rf(customerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.ONULocation)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(customerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: id
func (_m *ONULocationRepository) FindByID(id uint) (*entities.ONULocation, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entities.ONULocation
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*entities.ONULocation, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *entities.ONULocation); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.ONULocation)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByONUID provides a mock function with given fields: onuID
func (_m *ONULocationRepository) FindByONUID(onuID string) (*entities.ONULocation, error) {
	ret := _m.Called(onuID)

	if len(ret) == 0 {
		panic("no return value specified for FindByONUID")
	}

	var r0 *entities.ONULocation
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entities.ONULocation, error)); ok {
		return rf(onuID)
	}
	if rf, ok := ret.Get(0).(func(string) *entities.ONULocation); ok {
		r0 = rf(onuID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.ONULocation)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(onuID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindBySerialNumber provides a mock function with given fields: serial
func (_m *ONULocationRepository) FindBySerialNumber(serial string) (*entities.ONULocation, error) {
	ret := _m.Called(serial)

	if len(ret) == 0 {
		panic("no return value specified for FindBySerialNumber")
	}

	var r0 *entities.ONULocation
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entities.ONULocation, error)); ok {
		return rf(serial)
	}
	if rf, ok := ret.Get(0).(func(string) *entities.ONULocation); ok {
		r0 = rf(serial)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.ONULocation)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(serial)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: location
func (_m *ONULocationRepository) Update(location *entities.ONULocation) error {
	ret := _m.Called(location)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.ONULocation) error); ok {
		r0 = rf(location)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewONULocationRepository creates a new instance of ONULocationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewONULocationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ONULocationRepository {
	mock := &ONULocationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
