// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	entities "github.com/alijayanet/gembok-backend/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// PackageRepository is an autogenerated mock type for the PackageRepository type
type PackageRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: pkg
func (_m *PackageRepository) Create(pkg *entities.Package) error {
	ret := _m.Called(pkg)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.Package) error); ok {
		r0 = rf(pkg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *PackageRepository) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with no fields
func (_m *PackageRepository) FindAll() ([]*entities.Package, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*entities.Package
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*entities.Package, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*entities.Package); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Package)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: id
func (_m *PackageRepository) FindByID(id uint) (*entities.Package, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entities.Package
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*entities.Package, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *entities.Package); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Package)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByName provides a mock function with given fields: name
func (_m *PackageRepository) FindByName(name string) (*entities.Package, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for FindByName")
	}

	var r0 *entities.Package
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entities.Package, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) *entities.Package); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Package)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: pkg
func (_m *PackageRepository) Update(pkg *entities.Package) error {
	ret := _m.Called(pkg)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.Package) error); ok {
		r0 = rf(pkg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPackageRepository creates a new instance of PackageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPackageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PackageRepository {
	mock := &PackageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
