// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	entities "github.com/alijayanet/gembok-backend/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// RouterRepository is an autogenerated mock type for the RouterRepository type
type RouterRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: router
func (_m *RouterRepository) Create(router *entities.Router) error {
	ret := _m.Called(router)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.Router) error); ok {
		r0 = rf(router)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *RouterRepository) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindActive provides a mock function with no fields
func (_m *RouterRepository) FindActive() (*entities.Router, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindActive")
	}

	var r0 *entities.Router
	var r1 error
	if rf, ok := ret.Get(0).(func() (*entities.Router, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *entities.Router); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Router)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with no fields
func (_m *RouterRepository) FindAll() ([]*entities.Router, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*entities.Router
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*entities.Router, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*entities.Router); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Router)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: id
func (_m *RouterRepository) FindByID(id uint) (*entities.Router, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entities.Router
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*entities.Router, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *entities.Router); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Router)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: router
func (_m *RouterRepository) Update(router *entities.Router) error {
	ret := _m.Called(router)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.Router) error); ok {
		r0 = rf(router)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRouterRepository creates a new instance of RouterRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRouterRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RouterRepository {
	mock := &RouterRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
