// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	entities "github.com/alijayanet/gembok-backend/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// TroubleTicketRepository is an autogenerated mock type for the TroubleTicketRepository type
type TroubleTicketRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ticket
func (_m *TroubleTicketRepository) Create(ticket *entities.TroubleTicket) error {
	ret := _m.Called(ticket)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.TroubleTicket) error); ok {
		r0 = rf(ticket)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *TroubleTicketRepository) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: page, perPage
func (_m *TroubleTicketRepository) FindAll(page int, perPage int) ([]*entities.TroubleTicket, int64, error) {
	ret := _m.Called(page, perPage)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*entities.TroubleTicket
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int) ([]*entities.TroubleTicket, int64, error)); ok {
		return rf(page, perPage)
	}
	if rf, ok := ret.Get(0).(func(int, int) []*entities.TroubleTicket); ok {
		r0 = rf(page, perPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.TroubleTicket)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) int64); ok {
		r1 = rf(page, perPage)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(int, int) error); ok {
		r2 = rf(page, perPage)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByCustomerID provides a mock function with given fields: customerID
func (_m *TroubleTicketRepository) FindByCustomerID(customerID uint) ([]*entities.TroubleTicket, error) {
	ret := _m.Called(customerID)

	if len(ret) == 0 {
		panic("no return value specified for FindByCustomerID")
	}

	var r0 []*entities.TroubleTicket
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]*entities.TroubleTicket, error)); ok {
		return rf(customerID)
	}
	if rf, ok := ret.Get(0).(func(uint) []*entities.TroubleTicket); ok {
		r0 = rf(customerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.TroubleTicket)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(customerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: id
func (_m *TroubleTicketRepository) FindByID(id uint) (*entities.TroubleTicket, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entities.TroubleTicket
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*entities.TroubleTicket, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *entities.TroubleTicket); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.TroubleTicket)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByStatus provides a mock function with given fields: status, page, perPage
func (_m *TroubleTicketRepository) FindByStatus(status string, page int, perPage int) ([]*entities.TroubleTicket, int64, error) {
	ret := _m.Called(status, page, perPage)

	if len(ret) == 0 {
		panic("no return value specified for FindByStatus")
	}

	var r0 []*entities.TroubleTicket
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(string, int, int) ([]*entities.TroubleTicket, int64, error)); ok {
		return rf(status, page, perPage)
	}
	if rf, ok := ret.Get(0).(func(string, int, int) []*entities.TroubleTicket); ok {
		r0 = rf(status, page, perPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.TroubleTicket)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int, int) int64); ok {
		r1 = rf(status, page, perPage)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(string, int, int) error); ok {
		r2 = rf(status, page, perPage)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Update provides a mock function with given fields: ticket
func (_m *TroubleTicketRepository) Update(ticket *entities.TroubleTicket) error {
	ret := _m.Called(ticket)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.TroubleTicket) error); ok {
		r0 = rf(ticket)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTroubleTicketRepository creates a new instance of TroubleTicketRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTroubleTicketRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TroubleTicketRepository {
	mock := &TroubleTicketRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
